name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true

jobs:
  set-release-version:
    uses: Vaelow233/Quark-J8/.github/workflows/set-version.yml@master
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  build:
    needs: set-release-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout latest release tag
        id: tag_search
        run: |
          echo "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v6.3.0
        with:
          mode: COMMIT
          fromTag: ${{ steps.tag_search.outputs.latest_tag }}
          toTag: ${{ github.ref }}
          configuration: ".github/changelog_configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2.6.2
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          tag_name: v${{ inputs.version }}
          generate_release_notes: false
          draft: false
          prerelease: false
          target_commitish: master
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          name: Quark ${{ inputs.version }}
          preserve_order: true

  deploy-maven:
    needs: build
    uses: Vaelow233/Quark-J8/.github/workflows/deploy-maven.yml@master
    secrets: inherit

  deploy-gradle-plugin:
    needs: build
    uses: Vaelow233/Quark-J8/.github/workflows/deploy-gradle-plugin.yml@master
    secrets: inherit
